### PR TITLE
Combined Production+Exploration and Markerless Option

### PR DESCRIPTION
**Pull request by snoato**
This PR introduces two rule changes:

- first Production and Exploration phase are combined to a new longer Production phase with an Exploration period at the beginning of the game (during it production can start, but machine positions have to be discovered)
- the option to perform detection of machines without markers is introduced to the main game and the technicalities of it are specified

To achieve this:
- a new marker is added to the game which will be affixed to machines in order to indicate the presence of a machine without containing information on the type and color of the machine (this will be used if a team intends to not use the labels for detection)
- new interaction behavior with the refbox is defined (which needs to be implemented and documented in detail)

### CODE REVIEW

**Comment by teamsolidus** [comment]
I don't think that makes sense. Either one is able to detect the presence of a machine with vision or lidar. But a new marker in a markerless detection only to detect the presence of a machine, that is a step backwards and not comprehensible for the audience, and anything but industrial. Or probably I have not understood this correctly.

**Comment by TarikViehmann** [comment]
The reason for the new marker is that the other team might rely on markers generally and could be thrown off-guard by finding machines without markers. Thats how it was discussed in last years TC meeting. But if you feel that this is no concern we can also dont use any markers at all in that case

**Comment by teamsolidus** [comment]
Ok i see, then we just have no markers at all, if both teams want's to do the markerless variant. Or are the "light version marker" always there?

**Comment by TarikViehmann** [comment]
we could make it such that if both teams play without markers, then there are no markers at all, if only one does, then the opposing team can chose if the dummy markers should be used or no markers :thinking:

**Comment by chde** [comment]
> we could make it such that if both teams play without markers, then there are no markers at all, if only one does, then the opposing team can chose if the dummy markers should be used or no markers 🤔

Makes most sense, but please try to keep this short and sweat.

**Comment by pkohout** [comment]
How is it made sure that a team that plays marklerless does not use the markers of the other team? Since the machines are mirrored the team playing without markers could simply use the markers of the other teams? I would propose that we say that it is only possible if both teams want to play markerless.
But in order to "force" teams to migrate we could add a date where the markers will be depricated.

**Comment by pkohout** [comment]
also please clarify what is meant with: `new interaction behavior with the refbox is defined (which needs to be implemented and documented in detail)` or create a reference to the according refbox issue/PR

**Comment by snoato** [comment]
> also please clarify what is meant with: `new interaction behavior with the refbox is defined (which needs to be implemented and documented in detail)` or create a reference to the according refbox issue/PR

This is addressed in Tarik's PR: https://github.com/robocup-logistics/rcll-refbox/pull/120

**Comment by snoato** [comment]
> How is it made sure that a team that plays marklerless does not use the markers of the other team? Since the machines are mirrored the team playing without markers could simply use the markers of the other teams? I would propose that we say that it is only possible if both teams want to play markerless. But in order to "force" teams to migrate we could add a date where the markers will be depricated.

I don't think it should only be possible in that case, but I subscribe to the idea of deprication. By switching to the Aruco Library, we can more easily generate tags, so we could provide a selection of tags, and create a random assignment of tag numbers to machines. @TarikViehmann what's your input on that. Maybe that would be a bit too much to implement for this season.

**Comment by TarikViehmann** [comment]
Nah random selection of tags sounds a bit overkill and like a nightmare to pull off in practice (you need physical markers of different combinations, constantly swap them between games etc).
I thought that the usage of opponent tags is simply tolerated to at least kickstart the markerless detection. Sure, it is possible to rely on the opposing markers, but at that point, why bother with not using your own markers.... We could only allow markerless in case both teams agree, that might slow down the progress in that area as suddenly it only makes sense to progress if your opponent focuses on markerless detection as well.
I personally think a deadline to phase out all markers might not be a good idea (yet) 1) because no team actually solved the task yet 2) and having a mandatory markerless detection further increases the burden of teams to catch up in order to play the main competition

**Review by TarikViehmann — APPROVED** [review]

**Comment by TarikViehmann** [comment]
+1

**Pull request merged**
