### PR TITLE
Clarified paragraph regarding access to blocked zones

### PR DESCRIPTION
**Pull request by thomerz**
Added a sentence that clarifies that blocked zones of any machines must be reachable from any location on the field.

### CODE REVIEW

**Comment by morxa** [comment]
I rebased onto the latest master and fixed some issues found by the linter.

**Comment by morxa** [comment]
+1

**Comment by vcoelen** [comment]
+1

**Comment by teamsolidus** [comment]
+1

**Comment by timn** [comment]
Why did you close this when this was not merged, yet?

**Comment by teamsolidus** [comment]
+1

**Comment by morxa** [comment]
__Proposal accepted__
* in favor: 3
* abstentions: 0
* opposed: 0

**Pull request merged**
