### PR TITLE
added rules for simulation challange

### PR DESCRIPTION
**Pull request by pkohout**
This PR contains updates for the simulation challenge using the rcll-simulator.

### CODE REVIEW

**Comment by snoato** [comment]
Please make sure lines are <80 characters, otherwise the build tests won't pass.

**Comment by TarikViehmann** [comment]
+1

**Comment by snoato** [comment]
+1

**Comment by teamsolidus** [comment]
+1

**Comment by pkohout** [comment]
+1

**Comment by MbortoliDB** [comment]
+1

**Review by TarikViehmann — APPROVED** [review]

**Pull request merged**
