### PR TITLE
Add latex linter, filetype, and max linewidth checks

### PR DESCRIPTION
**Pull request by morxa**
1. Add a Makefile to
    * build the rulebook by invoking `latexmk`
    * run the latex linter `chktex` and make sure that there are no warnings
    * check that the file is encoded with UTF-8 without BOM (this tests the build error in #15 and gives a more explicit error message)
    * check that the maximum linewidth is 80
2. Adapt the rulebook to pass all the tests above
3. Add the tests to circleci so they are run automatically

### CODE REVIEW

**Comment by morxa** [comment]
This also splits the circleci tests into a build and a check test, so the required test will not be reported anymore. Once this PR is accepted, I will change the repository config to require those tests instead.

**Comment by MostafaGomaa** [comment]
Tested by running` latexmk -pdf rulebook.tex `
I like the workflow and the changes. Thanks for the effort :+1: 

Wondering though, since the commit https://github.com/robocup-logistics/rcll-rulebook/pull/16/commits/cb007e588ab651290d47baeeaf580b24fe6958b4 touches a lot of lines. Does it make more sense to merge this PR first or last? (relative to the other open PRS)

**Comment by morxa** [comment]
Thanks for reviewing!

Good question. I would merge this rather sooner than later, because I don't think the number of open PRs will not really reduce. I can help rebasing after this is merged.

Note that you don't actually need to run `latexmk` manually. Instead, there are the make targets `pdf` and `check`. Just running `make` should build the PDF.

**Comment by MostafaGomaa** [comment]
> Good question. I would merge this rather sooner than later, because I don't think the number of open PRs will not really reduce. I can help rebasing after this is merged.
>
sounds good
> Note that you don't actually need to run `latexmk` manually. Instead, there are the make targets `pdf` and `check`. Just running `make` should build the PDF.
oh right, thanks ^^

**Comment by morxa** [comment]
Merging, as there are no semantic changes, just reformatting

**Pull request merged**
