### PR TITLE
GitHub action compiling PDF

### PR DESCRIPTION
**Pull request by pkohout**
A simple action that compiles the rulebook on push and upload the pdf as artifact. Not sure if we should do this on every push, or only on master. Open for any ideas.

### CODE REVIEW

**Comment by pkohout** [comment]
just saw that there is already a circle-ci setup......^^

**Comment by pkohout** [comment]
I took a closer look at the circle ci and noticed that the builder (latex compiling image) has to be maintained by ourself. Since the github action is maintained by someone else (https://github.com/xu-cheng/latex-action) I think it will be less work to maintain in the long run. I would be in the favor of mergin this.

@snoato @TarikViehmann what do you think about this change?

**Comment by TarikViehmann** [comment]
I have no strong opinion on it, but the benefit of having the texlive image is that we can provide it to people who want to work on the rulebook without having a latex installation (we could a simple dev setup wrapper for it in the rulebook repo).
I am not sure if this is a strong concern as i assume it is not too diffiicult to obtain latex on any distro nowadays, but it might prevent some weird version conflicts or differences.
Also, the workload to maintain the livebuilder is minimal.
If you strongly prefer the github action route, i am open for the change,  otherwise i would suggest we stick to the current setup.

**Comment by pkohout** [comment]
The big advantage I see with the github aciton is that it also runs on a forked repository, not only on the main one. And yeah the reason why I came up with the action is because I did not had latex installed on my PC, and I did not wanted to do so.I guess if people edit the rulebook, and their related forks have already the final pdf as build artifact makes it quite easy to review changes since one can just read the final PDF without the need to check it out and build it.

**Comment by pkohout** [comment]
ok as soon as a PR is created circle CI also runs for forks. So I don't mind if we keep the action or not.

**Pull request closed without merging**
