### PR TITLE
Time limit and more zones/score for markerless machine recognition

### PR DESCRIPTION
**Pull request by thomerz**
Introduce a timelimit in the markerless machine recoginition task, such that teams need to speed up their recognition algorithms. Also increased the number of available machines to 4 for faster teams.

### CODE REVIEW

**Comment by MostafaGomaa** [comment]
I like the idea of linearly scaling a lot, since it creates more competition and encourages speedups like Till said, but is it possible that this might also give advantages to teams with better/faster driving over the actual recognition task. (If the bots start already infront of the machine I suppose that is not an issue, Do they?)

Bonus points sound like a good tradoff.  Maybe we always give the bonus based on breaking the last 'record'?

**Comment by morxa** [comment]
I rebased onto the latest master and fixes some issues found by the linter.

**Comment by morxa** [comment]
Afaik there are no pending changes, so I initiated voting.

**Comment by morxa** [comment]
+1

**Comment by timn** [comment]
+1

**Comment by teamsolidus** [comment]
+1

**Comment by morxa** [comment]
@robocup-logistics/technical-committee please vote!

**Comment by morxa** [comment]
**Proposal accepted**

* in favor: 3
* abstentions: 4
* opposed: 0

**Pull request merged**
